kind: Namespace
apiVersion: v1
metadata:
  name: netflix-clone-ns # Namespace Name
  labels:
    name: netflix-clone-ns
---
kind: SecurityGroupPolicy
apiVersion: vpcresources.k8s.aws/v1beta1
metadata:
  name: NetflixCloneSecurityGroup
  namespace: netflix-clone-ns
spec:
  podSelector:
    matchLabels:
      app: netflix-clone
  securityGroups:
    groupIds:
      - sg-0ed27de8dddafb2ae
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: netflix-clone
  labels:
    app: netflix-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-clone
  template:
    metadata:
      labels:
        app: netflix-clone
    spec:
      containers:
      - name: netflix-clone
        image: 956630439322.dkr.ecr.ap-south-1.amazonaws.com/netflix-ecr:netflix-clone-v1 # Docker Image URI
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 128m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-load-balancer
  namespace: netflix-clone-ns
spec:
  selector:
    app: netflix-clone
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer