apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: netflix-clone
    namespace: argocd
spec:
    project: default
    source:
        repoURL: 'https://github.com/rutwikdeshmukh/netflix-clone.git'
        path: manifests/
        targetRevision: main
    destination:
        server: 'https://AB80DCD201199E81748407672287B71F.yl4.ap-south-1.eks.amazonaws.com'
        namespace: default

