apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
spec:
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: 956630439322.dkr.ecr.ap-south-1.amazonaws.com/netflix-ecr:netflix-clone-v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netflix
spec:
  type: LoadBalancer
  selector:
    app: netflix
  ports:
  - name: http
    port: 80
    targetPort: 80